package com.org.simulation.ne;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

public class AddDialog extends JDialog{

	/**
	 * 
	 */
	  // Variables declaration - do not modify                     
    private JButton okButton;
  

	private JButton cancel;
    public JButton getCancel() {
		return cancel;
	}


	public void setCancel(JButton cancel) {
		this.cancel = cancel;
	}


	public JButton getApply() {
		return apply;
	}


	public void setApply(JButton apply) {
		this.apply = apply;
	}

	private JButton apply;
    private JComboBox<String> shelfModel;
	private JComboBox<String> slotNo;
    private JComboBox<String> cardCombo;
    private JComboBox<String> port;
    private JComboBox<String> facilityCombo;
    private JComboBox<String> wavelengthCombo;
    private JComboBox<String> serviceTypeCombo;
    private JComboBox<String> frequencyCombo;
    private JComboBox<String> diffrentialEncodingCombo;
    private JLabel jLabel11;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JTextField cdfi;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JComboBox<String> primaryCombo;
	private JComboBox<String> pecCombo;
    private JComboBox<String> modCombo;
    private JComboBox<String> profileCombo;
    private JComboBox<String> trafficCombo;
    private JTextField serialNo;

	public static final DefaultComboBoxModel<String> pktotnModel = new DefaultComboBoxModel<>(new String[] { "PTP", "ODUTTP", "ODUCTP", "TCMTTP"});
    public static final DefaultComboBoxModel<String> _100GMuxModel = new DefaultComboBoxModel<>(new String[] { "OTM2", "OTM4", "OTM6", "OTM10"});
    public static final DefaultComboBoxModel<String> _100GOCLDModel = new DefaultComboBoxModel<>(new String[] { "OC12", "OC48", "OC192", "ODU1"});
    public static final DefaultComboBoxModel<String> _EmotrModel = new DefaultComboBoxModel<>(new String[] { "ODU3", "STM4", "STM16", "STM64"});
    
	public static final DefaultComboBoxModel<String> pktotnpecModel = new DefaultComboBoxModel<>(new String[] { "NTK760MK", "NTK760MA", "NTK761AA", "NTK769AL"});
    public static final DefaultComboBoxModel<String> _100GMuxpecModel = new DefaultComboBoxModel<>(new String[] { "NTK539AA", "NTK537AA", "NTK538AB", "NTK536AJ"});
    public static final DefaultComboBoxModel<String> _100GOCLDpecModel = new DefaultComboBoxModel<>(new String[] { "NTK675AA", "NTK675AB", "NTK675AJ", "NTK675GT"});
    public static final DefaultComboBoxModel<String> _EmotrpecModel = new DefaultComboBoxModel<>(new String[] { "NTK428BB", "NTK429BA", "NTK427BK", "NTK424BL"});
    
    // End of variables declaration    
    // End of variables declaration           
	private static final long serialVersionUID = -5691446312404381153L;
	
	private ComboBoxListner listner = new ComboBoxListner();
    	
	public AddDialog(java.awt.Frame parent, boolean modal) {
		 super(parent, modal);
	        initComponents();		
	        setTitle("Add Dialog");
	}
	
	
	   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        okButton = new JButton();
        cancel = new JButton();
        apply = new JButton();
        shelfModel = new JComboBox<>();
        jLabel2 = new JLabel();
        slotNo = new JComboBox<>();
        jLabel3 = new JLabel();
        cardCombo = new JComboBox<>();
        jLabel4 = new JLabel();
        port = new JComboBox<>();
        jLabel5 = new JLabel();
        facilityCombo = new JComboBox<>();
        jLabel6 = new JLabel();
        wavelengthCombo = new JComboBox<>();
        jLabel7 = new JLabel();
        cdfi = new JTextField();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        serviceTypeCombo = new JComboBox<>();
        frequencyCombo = new JComboBox<>();
        jLabel10 = new JLabel();
        diffrentialEncodingCombo = new JComboBox<>();
        jLabel11 = new JLabel();
        primaryCombo = new JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        pecCombo = new JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        modCombo = new JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        profileCombo = new JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        trafficCombo = new JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        serialNo = new JTextField();

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("NE Shelf Model:");

        okButton.setText("OK");
        okButton.setActionCommand("OK");

        cancel.setText("Cancel");

        apply.setText("Apply");
        apply.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(18, 18, 18)
                .addComponent(apply)
                .addGap(18, 18, 18)
                .addComponent(cancel)
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(apply)
                    .addComponent(okButton))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        shelfModel.setModel(new DefaultComboBoxModel<>(new String[] { NeConstants.T_SERIES, NeConstants.S_SERIES}));

        jLabel2.setText("Slot No:");

        slotNo.setModel(new DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4","5", "6", "7", "8","9", "10", "11", "12"}));

        jLabel3.setText("Card:");

        cardCombo.setModel(new DefaultComboBoxModel<>(new String[] { "PKTOTN", "100GMUX", "100GOCLD","EMOTR"}));

        cardCombo.addActionListener(listner);
        
        jLabel4.setText("Port:");

        port.setModel(new DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10","12"}));

        jLabel5.setText("Facility:");

        facilityCombo.setModel(pktotnModel);

        jLabel6.setText("Wavelength:");

        wavelengthCombo.setModel(new DefaultComboBoxModel<>(new String[] { "1601.2", "1602.1", "1603.4", "1604.6", "1605.5" }));
        wavelengthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Customer Definend Identifier:");

        cdfi.setColumns(16);
        cdfi.setText("");
        cdfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Service Type:");

        jLabel9.setText("Frequency:(Hz)");

        serviceTypeCombo.setModel(new DefaultComboBoxModel<>(new String[] { "10G", "20G", "30G", "40G","100G"}));

        frequencyCombo.setModel(new DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40" }));

        jLabel10.setText("Diffrential Encoding:");

        diffrentialEncodingCombo.setModel(new DefaultComboBoxModel<>(new String[] { "HARD", "SOFT", "NONE"}));

        jLabel11.setText("Primary State:");

        primaryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IS", "OSS", "OSS-MA" }));
        primaryCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });

        jLabel12.setText("Provision Pec: ");

        pecCombo.setModel(pktotnpecModel);

        jLabel13.setText("MOD:");

        modCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QPSK", "BPSK", "100QPSK", "40BPSK" }));

        jLabel14.setText("Profile:");

        profileCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10G", "40GUNNI", "4X10G", "10GUII" }));

        jLabel15.setText("Trafic Status:");

        trafficCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO"}));

        jLabel16.setText("Serial No:");

        serialNo.setColumns(15);
        serialNo.setText("SFWB"+System.currentTimeMillis());
     
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facilityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wavelengthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serviceTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frequencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diffrentialEncodingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slotNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shelfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primaryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pecCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trafficCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(292, 292, 292))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(shelfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slotNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cardCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(primaryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pecCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(modCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(trafficCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(serialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(facilityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(serviceTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(frequencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wavelengthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(diffrentialEncodingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cdfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pack();
        }                      

    protected void jComboBox10ActionPerformed(ActionEvent evt) {
		
	}


	public JButton getOkButton() {
  		return okButton;
  	}
    

    private void jButton3ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField2ActionPerformed(ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jComboBox6ActionPerformed(ActionEvent evt) {                                           
        // TODO add your handling code here:
    }            

    class ComboBoxListner implements ActionListener{

    	@Override
    	public void actionPerformed(ActionEvent e) {
    		if(e.getSource()==cardCombo){
    			String card = (String)cardCombo.getSelectedItem();
    			if("100GOCLD".equals(card)){
    				facilityCombo.setModel(_100GOCLDModel);
    				pecCombo.setModel(_100GOCLDpecModel);
    			}else if("PKTOTN".equals(card)){
    				facilityCombo.setModel(pktotnModel);
    				pecCombo.setModel(pktotnpecModel);
    			}else if("100GMUX".equals(card)){
    				facilityCombo.setModel(_100GMuxModel);
    				pecCombo.setModel(_100GMuxpecModel);
    			}else if("EMOTR".equals(card)){
    				facilityCombo.setModel(_EmotrModel);
    				pecCombo.setModel(_EmotrpecModel);
    			}
    		}
    	}
    }
    public JComboBox<String> getShelfModel() {
  		return shelfModel;
  	}


  	public JComboBox<String> getSlotCombo() {
  		return slotNo;
  	}


  	public JComboBox<String> getCardCombo() {
  		return cardCombo;
  	}


  	public JComboBox<String> getPortCombo() {
  		return port;
  	}


  	public JComboBox<String> getfacility() {
  		return facilityCombo;
  	}


  	public JComboBox<String> getWavelengthCombo() {
  		return wavelengthCombo;
  	}


  	public JComboBox<String> getServiceTypeCombo() {
  		return serviceTypeCombo;
  	}


  	public JComboBox<String> getFrequencyCombo() {
  		return frequencyCombo;
  	}


  	public JComboBox<String> getDiffrentialEncodingCombo() {
  		return diffrentialEncodingCombo;
  	}
  	
    public JTextField getCdfi() {
 		return cdfi;
 	}
    
    public JComboBox<String> getSlotNo() {
		return slotNo;
	}


	public JComboBox<String> getPrimaryCombo() {
		return primaryCombo;
	}


	public JComboBox<String> getPecCombo() {
		return pecCombo;
	}


	public JComboBox<String> getModCombo() {
		return modCombo;
	}


	public JComboBox<String> getProfileCombo() {
		return profileCombo;
	}


	public JComboBox<String> getTrafficCombo() {
		return trafficCombo;
	}


	public JTextField getSerialNo() {
		return serialNo;
	}
}
