package spring.state.machine.statemachinedomain;

public enum MStates {
	RECEIVED, POSFAIL, POSPASS, VALIDATION, VALIDATION_OK, VALIDATION_ERROR, INIT_PROCESS, REF_TRANS_FORK, INIT_PROCESS_COMPLETE, REF_DATA_PROCESS, REF_DATA_PROCESS_COMPLETE, TRANS_DATA_PROCESS, TRANS_DATA_PROCESS_COMPLETE, TRANS_FORK, TRANS_TLIVE, TRANS_TLIVE_COMPLETE, TRANS_TPLIVE, TRANS_TPLIVE_COMPLETE, TRANS_FORK_JOIN, REF_TRANS_FORK_JOIN

}
